[build]
  command = "npm run build"
  publish = "dist"
  functions = "server"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 